# Random code tests

In [6]:
import numpy as np
import torch

In [4]:
a = np.random.rand(3, 4)
print(a)    

[[0.2073397  0.76421832 0.54361166 0.23927924]
 [0.96796034 0.89794903 0.21717962 0.39283789]
 [0.30073227 0.45203694 0.08193011 0.2613282 ]]


In [9]:
t = torch.rand(3, 4)
print(t)

tensor([[0.4423, 0.4818, 0.4250, 0.9799],
        [0.8734, 0.7332, 0.6479, 0.0032],
        [0.0993, 0.4554, 0.2235, 0.1854]])


In [10]:
t.clamp(0.2, 0.8)

tensor([[0.4423, 0.4818, 0.4250, 0.8000],
        [0.8000, 0.7332, 0.6479, 0.2000],
        [0.2000, 0.4554, 0.2235, 0.2000]])

In [12]:
t.clamp(0.5)

tensor([[0.5000, 0.5000, 0.5000, 0.9799],
        [0.8734, 0.7332, 0.6479, 0.5000],
        [0.5000, 0.5000, 0.5000, 0.5000]])